{% set name = "pycompss" %}
{% set version = "2.5" %}
{% set sha256 = "557a6f16af1114f32973ae6ec1e52cf6e559bc3a8ff1923f2cfe2bb29230cfbb" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://compss.bsc.es/repo/sc/stable/COMPSs_{{ version }}.tar.gz
  sha256: "{{ sha256 }}"
  patches:
    - install.patch

build:  
  number: 0
  skip: True  # [osx]
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf
    - libtool
    - automake
    - autoconf
    - make
    - pkg-config
    - bison
    - flex
    - libtool
  host:
    - gmp
    - pip
    - setuptools
    - python 
    - boost
    - openjdk =8
    - libxml2
  run:
    - python
    - openjdk =8
    - libxml2

test:
  commands:
    - runcompss --version

about:
  home: http://compss.bsc.es
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: COMP Superscalar Programming Framework
  doc_url: https://www.bsc.es/research-and-development/software-and-apps/software-list/comp-superscalar/documentation
  dev_url: https://github.com/bsc-wdc/compss

extra:
  recipe-maintainers:
    - stian
    - lezzidan
