{% set name = "pycompss" %}
{% set version = "2.4" %}
{% set sha256 = "1b6d1712345b6201d3683e01189fef2c9ea7b02a8dd8e47c666b72f5750e20aa" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://compss.bsc.es/repo/sc/stable/COMPSs_{{ version }}.tar.gz
  sha256: "{{ sha256 }}"
  patches:
    - install.patch

build:  
  number: 0
  skip: True  # [osx]
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf
    - libtool
    - automake
    - autoconf
    - make
    - pkg-config
    - bison
    - flex
    - libtool
  host:
    - gmp
    - pip
    - setuptools
    - python 
    - boost
    - openjdk =8
    - libxml2
  run:
    - python
    - openjdk =8
    - libxml2

test:
  commands:
    - echo "Finished" 

about:
  home: http://compss.bsc.es
  license: Apache-2.0
  license_family: APACHE
  license_file: 
  summary: COMP Superscalar Programming Framework
  doc_url:
  dev_url: https://github.com/bsc-wdc/compss

extra:
  recipe-maintainers:
    - stian
    - lezzidan
