{% set name = "pycompss" %}
{% set version = "2.6" %}
{% set sha256 = "a70fa36a38a97165278f3cf9b752f3031a05925c38463c63a153da1ff281186a" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://compss.bsc.es/repo/sc/stable/COMPSs_{{ version }}.tar.gz
  sha256: "{{ sha256 }}"
  patches:
    - install.patch

build:  
  number: 0
  skip: True  # [osx]
  skip: True  # [osx_64]
  skip: True  # [win]
  skip: True  # [win_64]
  rpaths:
    - lib/
    - jre/lib/amd64/
    - jre/lib/amd64/server/
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf
    - libtool
    - automake
    - autoconf
    - make
    - pkg-config
    - bison
    - flex
    - libtool
    - openjdk =8
  host:
    - gmp
    - pip
    - setuptools
    - python 
    - boost
    - openjdk =8
    - libxml2
  run:
    - python
    - openjdk =8
    - libxml2
    - boost-cpp

test:
  commands:
    - runcompss --version

about:
  home: http://compss.bsc.es
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: COMP Superscalar Programming Framework
  doc_url: https://www.bsc.es/research-and-development/software-and-apps/software-list/comp-superscalar/documentation
  dev_url: https://github.com/bsc-wdc/compss

extra:
  recipe-maintainers:
    - stian
    - lezzidan
